# services:
#   app1:
#     image: nginx:latest
#     ports:
#       - 80


#   app2:
#     image: busybox:latest
#     command: sleep infinity

services:
  busybox_ipv4:
    image: busybox
    command: sleep 3600
    networks:
      - ipv4_net

  busybox_ipv6:
    image: busybox
    command: sleep 3600
    networks:
      - ipv6_net

networks:
  ipv4_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"  # Disable IPv6
    ipam:
      config:
        - subnet: 192.168.1.0/24  # IPv4 subnet

  ipv6_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"  # Enable IPv6
    ipam:
      driver: default
      config:
        - subnet: fd00:dead:beef::/64  # IPv6 subnet
        # No IPv4 subnet is defined, so only IPv6 is available