services:
  nginx1:
    image: nginx:1.21
    ports:
      - "8081:80"
    volumes:
      - ./nginx1/html:/usr/share/nginx/html
    networks:
      - nw1

  nginx2:
    image: nginx:1.21
    ports:
      - "8082:80"
    volumes:
      - ./nginx2/html:/usr/share/nginx/html
    networks:
      - nw2

  alpine1:
    image: alpine:latest
    command: sleep infinity
    networks:
      - nw1
      - nw2
    tty: true

networks:
  nw1:
    driver: bridge

  nw2:
    driver: bridge