services:
  fastapi-app:
    image: python:3.10-slim
    command: >
      sh -c "pip install fastapi uvicorn && 
             uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - fast
      - web
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-http.rule=Host(`localhost`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      - "traefik.http.routers.fastapi-http.middlewares=redirect-to-https"
      - "traefik.http.routers.fastapi-https.rule=Host(`localhost`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      - "traefik.http.routers.fastapi-https.entrypoints=websecure"
      - "traefik.http.routers.fastapi-https.tls=true"

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/dynamic.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs" 
      - "./dynamic.yml:/dynamic.yml"
    networks:
      - reverse
      - web

networks:
  fast:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
  reverse:
    driver: bridge
  web:
    driver: bridge